# Datos del emisor
issuer_url = https://www.issuer.org
issuer_id = https://www.blockcerts.org/samples/2.0/issuer-testnet.json

# Directorios
data_dir = sample_data
template_dir = certificate_templates
template_file_name = test.json
unsigned_certificates_dir = unsigned_certificates
roster = rosters/roster_testnet.csv

# Campo nonce (REQUERIDO para Blockcerts V3)
additional_global_fields = {"fields": [{"path": "$.nonce","value": "sec:nonce"}]}

# Campos personalizados por recipiente
additional_per_recipient_fields = {"fields": [{"path": "$.credentialSubject.finalGrade","value": "*|FINAL_GRADE|*","csv_column": "final_grade"}]}
